// THIS IS JUST THE FIBONACCI SEQUENCE DONE WITH JAVASCRIPT. PRETTY SIMPLE SCRIPT
VAR FIBONACCI = FUNCTION(N) {
    IF(N < 1) { RETURN 0;}
    ELSE IF(N == 1 || N == 2) { RETURN 1;}
    ELSE IF(N > 2) { RETURN FIBONACCI(N - 1) + FIBONACCI(N - 2);}
};

// FIBONACCI: CLOSED FORM EXPRESSION
// HTTP://EN.WIKIPEDIA.ORG/WIKI/GOLDEN_RATIO#RELATIONSHIP_TO_FIBONACCI_SEQUENCE
VAR FIBONACCI2 = FUNCTION(N) {
    VAR PHI = (1 + MATH.SQRT(5))/2;
    RETURN MATH.ROUND((MATH.POW(PHI, N) - MATH.POW(1-PHI, N))/MATH.SQRT(5));
};

// FIND FIRST K FIBONACCI NUMBERS VIA BASIC FOR LOOP
VAR FIRSTKFIB = FUNCTION(K) {
    VAR I = 1;
    VAR ARR = [];
    FOR(I = 1; I < K+1; I++) {
        ARR.PUSH(FIBONACCI(I));
    }
    RETURN ARR;
};

// PRINT TO CONSOLE
VAR FMT = FUNCTION(ARR) {
    RETURN ARR.JOIN(" ");
};

VAR K = 25;
CONSOLE.LOG("FIRSTKFIB(" + K + ")");
console.log(fmt(firstkfib(k)));
